---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %/VignetteIndexEntry{Vignette Title}
  %/VignetteEngine{knitr::rmarkdown}
  %/VignetteEncoding{UTF-8}
---

Package eqv allows clean up & visualization of the NOAA earthquake dataset.  The document describes some of the functionalities available in the eqv package.


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(chron)
library(stringr)
library(ggplot2)
library(leaflet)
#library(eqv)
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/eq_clean_data.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/eq_location_clean.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/geom_timeline.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/GeomTimeline.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/GeomTimelineLabel.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/geom_timeline_label.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/theme_timeline.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/eq_map.R")
source("C:/Users/nndigh/Desktop/Educational/coursera/Mastering Software Development in R/CAPSTONE/package/eqv/R source code/eq_create_label.R")
filename <- system.file("extdata/signif.txt", package = "eqv")
data <- readr::read_delim(filename, delim = "\t")
data %>%
  eq_clean_data() %>%
  eq_location_clean %>%
  filter(COUNTRY %in% c("INDIA", "ITALY"), YEAR > 1990) %>%
  ggplot(aes(x  = DATE, y = COUNTRY,color = as.numeric(TOTAL_DEATHS),size = as.numeric(EQ_PRIMARY)))+ 
  geom_timeline() + 
  geom_timeline_label(aes(label = LOCATION_NAME), n_max = 5) + 
  theme_timeline()

```

# Example below shows use if leaflet mapping function

```{r echo=FALSE, message=FALSE}
data %>% 
  eq_clean_data() %>% 
  dplyr::filter(COUNTRY == "MEXICO" & lubridate::year(DATE) >= 2000) %>% 
  dplyr::mutate(popup_text = eq_create_label(.)) %>% 
  eq_map(annot_col = "popup_text")
```
